@server=http://localhost:4004
@username=alice
@password=


### ListOfBooks
# @name ListOfBooks_GET
GET {{server}}/browse/ListOfBooks
Authorization: Basic {{username}}:{{password}}


### ListOfBooks
# @name ListOfBooks_POST
POST {{server}}/browse/ListOfBooks
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "85091151-8bf1-4265-836b-679a48d4d904",
  "author": {
    "ID": "99736515-f1f8-415d-aad2-430b6fd510f8"
  },
  "title": "title-8509115",
  "genres": {
    "ID": 3650835
  },
  "stock": 49,
  "price": 7884715.84,
  "isbn": "isbn-8509115",
  "currency": "09115",
  "publisher_ID": "publisher_ID-8509115",
  "createdAt": "2000-10-20T05:00:00.000Z",
  "createdBy": "createdBy.52dob@example.org",
  "modifiedAt": "2018-04-02T05:00:00.000Z",
  "modifiedBy": "modifiedBy.52dob@example.com"
}


### ListOfBooks
# @name ListOfBooks_PATCH
PATCH {{server}}/browse/ListOfBooks/85091151-8bf1-4265-836b-679a48d4d904
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "85091151-8bf1-4265-836b-679a48d4d904",
  "author": {
    "ID": "99736515-f1f8-415d-aad2-430b6fd510f8"
  },
  "title": "title-8509115",
  "genres": {
    "ID": 3650835
  },
  "stock": 49,
  "price": 7884715.84,
  "isbn": "isbn-8509115",
  "currency": "09115",
  "publisher_ID": "publisher_ID-8509115",
  "createdAt": "2000-10-20T05:00:00.000Z",
  "createdBy": "createdBy.52dob@example.org",
  "modifiedAt": "2018-04-02T05:00:00.000Z",
  "modifiedBy": "modifiedBy.52dob@example.com"
}


### ListOfBooks
# @name ListOfBooks_DELETE
DELETE {{server}}/browse/ListOfBooks/85091151-8bf1-4265-836b-679a48d4d904
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Genres
# @name Genres_GET
GET {{server}}/browse/Genres
Authorization: Basic {{username}}:{{password}}


### Books
# @name Books_GET
GET {{server}}/browse/Books
Authorization: Basic {{username}}:{{password}}


### Books
# @name Books_POST
POST {{server}}/browse/Books
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "18508812-1ee7-43ee-945f-1a7386e02ba5",
  "author": "author-18508812",
  "title": "title-18508812",
  "descr": "descr-18508812",
  "genres": {
    "ID": 3650835
  },
  "stock": 47,
  "price": 2454760.01,
  "isbn": "isbn-18508812",
  "currency": {
    "code": "846"
  },
  "publisher_ID": "publisher_ID-18508812",
  "modifiedAt": "2020-06-18T05:00:00.000Z",
  "modifiedBy": "modifiedBy.b0pho@example.org"
}


### Books
# @name Books_PATCH
PATCH {{server}}/browse/Books/18508812-1ee7-43ee-945f-1a7386e02ba5
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "18508812-1ee7-43ee-945f-1a7386e02ba5",
  "author": "author-18508812",
  "title": "title-18508812",
  "descr": "descr-18508812",
  "genres": {
    "ID": 3650835
  },
  "stock": 47,
  "price": 2454760.01,
  "isbn": "isbn-18508812",
  "currency": {
    "code": "846"
  },
  "publisher_ID": "publisher_ID-18508812",
  "modifiedAt": "2020-06-18T05:00:00.000Z",
  "modifiedBy": "modifiedBy.b0pho@example.org"
}


### Books
# @name Books_DELETE
DELETE {{server}}/browse/Books/18508812-1ee7-43ee-945f-1a7386e02ba5
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Currencies
# @name Currencies_GET
GET {{server}}/browse/Currencies
Authorization: Basic {{username}}:{{password}}


### submitOrder
# @name submitOrder_POST
POST {{server}}/browse/submitOrder
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "book": "19032785-0f86-4408-b0d4-3b8f86ce457a",
  "quantity": 8
}
